version: "3.9"

services:
  milvus:
    image: milvusdb/milvus:v2.4.0
    container_name: milvus-lite
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-lite-etcd
    command: ["/usr/local/bin/etcd", "-advertise-client-urls", "http://0.0.0.0:2379", "-listen-client-urls", "http://0.0.0.0:2379"]

  minio:
    image: minio/minio:RELEASE.2024-12-05T06-33-25Z
    container_name: milvus-lite-minio
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    command: ["server", "/data"]
    volumes:
      - minio-lite:/data

volumes:
  minio-lite:
